okta/okta-management-openapi-spec

.gitignore
dist/spec.json
dist/spec.yaml
package.json
resources/spec.yaml

1. Added  missing `method` [field](https://developer.okta.com/docs/reference/api/inline-hooks/#request-example-3) to InlineHookChannelConfig.
2. Added missing `slo` [field](https://developer.okta.com/docs/reference/api/apps/#single-logout-object) to [custom SAML application settings](https://developer.okta.com/docs/reference/api/apps/#add-custom-saml-application).

Added missing fields

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Added [missing property](https://developer.okta.com/docs/reference/api/apps/#service-provider-certificate) from [custom SAML application settings](https://developer.okta.com/docs/reference/api/apps/#settings-9)

Add missing spCertificate

---

CHANGELOG.md
dist/spec.json
dist/spec.yaml
package.json

Adds Changelog
Resolves #5 and #6

Update for 2.2.4 release

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Add private_key_jwt to OAuthEndpointAuthenticationMethod

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Add FIDO Factor provider type

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Added missing field "type" to OpenIdConnectApplicationIssuerMode

Added missing field to OpenIdConnectApplicationIssuerMode

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

OktaSignOnPolicyConditions should implement PolicyRuleConditions
PasswordPolicyConditions should implement PolicyRuleConditions

Interfaces updated

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Method added UserType.replaceUserType

Method added UserType.replaceUserType

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Note, this change:
```yaml
x5t#S256:
'x5t#S256':
```
appeared after `yarn build`, i.e. should be fine, but please, take a look

Change 'hotp' to 'token:hotp' in UserFactor

---

dist/spec.json
dist/spec.yaml
package.json
yarn.lock

Reverts https://github.com/okta/okta-management-openapi-spec/pull/27/files version change.

Updates version number

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

See the docs here https://developer.okta.com/docs/reference/api/apps/#settings-10

Added wildcard_redirect field to the OAuth app settings

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Issue: https://github.com/okta/okta-sdk-java/issues/593

OKTA-406629: update filter parameter name

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Remove DomainResponse, DomainResponseList, and DomainLinks.

Updates in Domains API

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Official Docs https://developer.okta.com/docs/reference/api/apps/#app-settings

Added admin notes to the app settings object

---

dist/spec.json
dist/spec.yaml
package.json
resources/spec.yaml

Related to https://github.com/okta/okta-sdk-python/pull/223
https://oktainc.atlassian.net/browse/OKTA-419410

Update description of "get_group" method

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

[Official docs](https://developer.okta.com/docs/reference/api/apps/#visibility-object)

Added autoLaunch property to ApplicationVisibility object

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

[Official Documentation](https://developer.okta.com/docs/reference/api/schemas/#group-schema-operations) might be missing some of the fields (sam as for UserSchema)

(OKTA-394188) Added operations for Group Schema

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

This is the same as GET `/api/v1/groups/{groupId}/roles/{roleId}`, but for user

Add GetUserRole

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Added missing GROUP_MEMBERSHIP_ADMIN to RoleType

---

dist/spec.json
dist/spec.yaml
package.json
resources/spec.yaml

Python SDK generated and ITs provided - https://github.com/okta/okta-sdk-python/pull/238

Add missing "app" authenticator type

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

https://github.com/okta/okta-sdk-java/issues/634
- https://developer.okta.com/docs/reference/api/idps/#identity-provider-social-authentication-token-object
- https://datatracker.ietf.org/doc/html/draft-ietf-oauth-token-exchange-07#section-3

Corrected `tokenType` in social auth token object to string type

---

dist/spec.json
dist/spec.yaml
package.json
resources/spec.yaml

- method getRole should belong to the User object
- method getOrgContactTypes should belong to the Client object

Java SDK alignment for v2.7.x

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Add missing federated type to authenticatorType spec

Add federated Authenticator Type to Spec

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Addresses https://github.com/okta/okta-sdk-golang/issues/259

Clearer articulation of user deactivation as pointed out in issue #259

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Spec for update authenticator resource and create named authenticators.
Golang SDK PR:
https://github.com/okta/okta-sdk-golang/pull/264
IT:
https://github.com/okta/okta-sdk-golang/blob/mm-refine-authenticators/tests/integration/authenticators_test.go

`PUT /api/v1/authenticators/{id}` and named authenticators.

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

This PR adds missing value `LOGO_ON_FULL_WHITE_BACKGROUND` to enum `EndUserDashboardTouchPointVariant` as described here https://developer.okta.com/docs/reference/api/brands/#theme-api-objects

Add missing touch point variant.

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Change `HIGH_RISK_ALWAYS` -> `HIGH_RISK_ONLY`, https://oktainc.atlassian.net/browse/OKTA-444823

Fix RequiredEnum, related to OKTA-444823

---

dist/spec.json
dist/spec.yaml
package.json
resources/spec.yaml

Issue addressed:
Since `AccessPolicyRuleConditions` inherits `PolicyRuleConditions` and has override method `getDevice()` the return type for `getDevice()` method should has covariant return type. Therefore, `DeviceAccessPolicyRuleCondition` should inherit `DevicePolicyRuleCondition`.

BrandAPI: fixes for Java SDK

---

CHANGELOG.md
dist/spec.json
dist/spec.yaml
lib/generator.js
package.json
resources/spec.yaml

- Updates responses section of `sendTestEmail` to be 204 to reflect the API

Changes send test email response to a 204

---

CHANGELOG.md
dist/spec.json
dist/spec.yaml
lib/generator.js
resources/spec.yaml

Co-authored-by: releng-internal-okta <eng_releng_internal@okta.com>
Co-authored-by: Shuo Wu <wushuo2010@gmail.com>

Merges 2.11.1 into master

---

CHANGELOG.md
dist/spec.json
dist/spec.yaml
resources/spec.yaml

- Adds model `IframeEmbedScopeAllowedApps`
- Updates `ScopeType` to include option `IFRAME_EMBED`

Update trusted origin

---

CHANGELOG.md
dist/spec.json
dist/spec.yaml
resources/spec.yaml

- Add Update Application Policy Path
- `PUT /api/v1/apps/{applicationId}/policies/{policyId}`
- operation added `updateApplicationPolicy`
See Docs: https://github.com/okta/okta-management-openapi-spec/pull/130

Add support for update application policy

---

package.json

`2.12.1` was not released yet - reverting bump to `12.2.2`

set package version back to 2.12.1

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Reopened to attempt to address CI issue.  Originally reviewed on https://github.com/okta/okta-management-openapi-spec/pull/133

OKTA-498007: add search param to list groups

---

CHANGELOG.md

Prep v2.13.0 release

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

The Verification Method model is missing inactivityPeriod property:
https://developer.okta.com/docs/reference/api/policy/#verification-method-object
Generated in okta-sdk-golang: https://github.com/okta/okta-sdk-golang/pull/315

Verification Method model is missing inactivityPeriod property

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Added OKTA_MANAGED and associated validation statuses

OPS-214923: Update CustomDomain statuses

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Ref: https://developer.okta.com/docs/reference/api/users/#list-all-users
Background Issue: https://github.com/okta/okta-sdk-java/issues/718

Update `list users` API desc

---

resources/3.0/idp.yaml
resources/3.0/management.yaml
resources/3.0/oauth.yaml

OpenAPI 3.0 specification update for 2023.01.0-begin-190-ge0ea56fcdd57

RELEASE for 2023.01.0-begin-190-ge0ea56fcdd57

---

dist/spec.json
dist/spec.yaml
resources/spec.yaml

Adding DYNAMIC issuer mode

---

dist/spec.json
dist/spec.yaml
resources/3.0/management.yaml
resources/spec.yaml

Bringing in PRs from the community.
Closes #164
Closes #160
Closes #152
Closes #153
Closes #150
Closes #124

Community PRs
