okta/okta-management-openapi-spec

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Adding missing field into OAuth 2.0 client application 
- [OAuth 2.0 application settings](https://developer.okta.com/docs/reference/api/apps/#settings-10)
- [idp-initiated-login-object](https://developer.okta.com/docs/reference/api/apps/#idp-initiated-login-object)
> Add IdP Initiated Login Field

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
This endpoint is now GA and needs to be added to the spec: https://developer.okta.com/docs/reference/api/threat-insight/
> OKTA-369793 Add ThreatInsight API to OpenAPI spec

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
This fixes the issue when generating SDK:
```
okta-sdk-python/openapi/templates/index.js:143
let tag = operation.tags[0];
^
TypeError: Cannot read property '0' of undefined
```
> Added missing tag

- .gitignore
- .travis.yml
- README.md
- package.json
- yarn.lock
- I feel this is nice.
https://haishengwu-okta.github.io/okta-management-openapi-spec/
- Given we checked the file, not sure if it's worth to hook with CI atm. Seems ideal approach is CI (bacon) auto push to `gh-pages` branch at every `main` build?
Update Mar 16
- enable travis to auto update gh-pages
- can check details at my fork 
- deployment history: https://github.com/haishengwu-okta/okta-management-openapi-spec/deployments/activity_log?environment=github-pages
- travis build: https://travis-ci.com/github/haishengwu-okta/okta-management-openapi-spec/builds
> Redoc + Github Page

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Java supports covariant return types for overridden methods. This means an overridden method may have a more specific return type. That is, as long as the new return type is assignable to the return type of the method you are overriding, it's allowed.
That is why we need to have next changes:
- `OktaSignOnPolicyRuleActions` and `PasswordPolicyRuleActions` should implement `PolicyRuleActions`
- `OktaSignOnPolicyRuleConditions` and `PasswordPolicyRuleConditions` should implement `PolicyRuleConditions`
The Interface `OktaSignOnPolicyRule` extends `PolicyRule` interface.
The `PolicyRule` interface has property actions. A getter for this property should have a return type `PolicyRuleActions`.
The `OktaSignOnPolicyRule` also has property actions. A getter for this property should have the …
> Interfaces need to be updated for compatibility with Java SDK

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
This PR solving an inconsistency in `activateNetworkZone` and `deactivateNetworkZone` methods syntax for the `NetworkZone` object in API.
openapi-spec describes the return type for this method as `void` but the actual call returning a `NetworkZone` object.
PR for Java Mgmt SDK: https://github.com/okta/okta-sdk-java/pull/572/files#diff-003145e24599013aff48cf944b56535ef1d263df510788d912f961d256dcbfbaR181-R188
> Response type for activateNetworkZone and deactivateNetworkZone

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
This PR related to [Add Domains API endpoints to open API spec. OKTA-387064](https://github.com/okta/okta-management-openapi-spec/pull/45) and [Update Domains API. OKTA-406710](https://github.com/okta/okta-management-openapi-spec/pull/48)
Operations `deleteDomain`, `getDomain` and `verifyDomain` could not be located inside a Domain object due the ID field is not exists in it.
The `createCertificate` operation should belong to the `DomainCertificate` object.
> Domain API: Java SDK compatibility fixes

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
The response for the `listDomains()` method doesn't require a new object.
Code could be simplified. Documentation is [here](DomainListResponse)
> DomainListResponse is not defined in docs and could be removed

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Property name inconsistent with the [documentation](https://developer.okta.com/docs/reference/api/domains/#usage-examples)
`certificateSourceType` is a correct name
> property naming fix

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
API response:
```
"actions": {
"token": {
"accessTokenLifetimeMinutes": 60,
"refreshTokenLifetimeMinutes": 0,
"refreshTokenWindowMinutes": 10080,
"inlineHook": {
"id": "cal10unah02MoSC5u0h8"
}
}
}
```
> Added missing field to the auth server policy rule

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
* `/api/v1/policies` now returns correct model `'#/definitions/Policy'` (instead of `"#/definitions/AuthorizationServerPolicy"`)
* reverted changes regarding `DomainListResponse`
> Fixed policies and reverted domains

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
List of changes:
- Method `getContactUser` should belong to `client`
- Methods `optInUsersToOktaCommunicationEmails` and `optOutUsersFromOktaCommunicationEmails` should belong to `OrgOktaCommunicationSetting`
- Methods `extendOktaSupport`, `grantOktaSupport` and `revokeOktaSupport` should belong to `OrgOktaSupportSettingsObj`
- Methods `hideEndUserFooter` and `showEndUserFooter` should belong to `OrgPreferences`
> Improvements for Java SDK

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Java SDK generated code:
Earlier:
```
/**
* Enum issuerMode
*/
public enum IssuerModeEnum {
ORG_URL("ORG_URL"),
CUSTOM_URL_DOMAIN("CUSTOM_URL_DOMAIN");
private String value;
IssuerModeEnum(String value) {
this.value = value;
}
@Override
public String toString() {
return String.valueOf(value);
}
}
```
Now:
```
/**
* Enum issuerMode
*/
public enum IssuerModeEnum {
ORG_URL("ORG_URL"),
CUSTOM_URL("CUSTOM_URL");
private String value;
IssuerModeEnum(String value) {
this.value = value;
}
@Override
public String toString() {
return String.valueOf(value);
}
}
```
> Correct `CUSTOM_URL` `IdentityProvider.issuerMode` value

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Per [API doc](https://developer.okta.com/docs/reference/api/authenticators-admin/#activate-an-authenticator), `activate` and `deactivate` authenticator must return `Authenticator` object type. But the current version of the spec does not define so. 
```
/**
* 
* Success
*/
@javax.annotation.Generated(
value    = "com.okta.swagger.codegen.OktaJavaClientApiCodegen",
date     = "2021-09-22T09:27:54.778-05:00",
comments = "POST - /api/v1/authenticators/{authenticatorId}/lifecycle/activate")
void activate();
/**
* 
* Success
*/
@javax.annotation.Generated(
value    = "com.okta.swagger.codegen.OktaJavaClientApiCodegen",
date     = "2021-09-22T09:27:54.778-05:00",
comments = "POST - /api/v1/authenticators/{authenticatorId}/lifecycle/deactivate")
void deactivate();
```
``` …
```
> fix missing return type issue with authenticators api

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Putting org operations on org settings crud.
Needed for okta-sdk-golang to be able to have methods for `/api/v1/org` and `/api/v1/org/*`
Corresponds to okta-sdk-golang PR https://github.com/okta/okta-sdk-golang/pull/261
> Put org operations on org settings crud.

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- package.json
- resources/spec.yaml
This update add the OrgSettings operations.  This is to address Java's broken IT's due to the way they were built.
There still may be an issue with duplicated model operations, and if that is the case, we should remove all duplicates from outside of `OrgSettings` model.
This is built as a patch release 2.8.1 and should be merged into the 2.8 branch.  Once released, we need to port these changes into the 2.9/master branch as well.
Edit:  Were removing duplicates from inside of `OrgSettings` for backwards compat issues
> Updates x-okta-operations for OrgSettings model

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
The `updateBrandTheme ` method works incorrectly.
According to [docs](https://developer.okta.com/docs/reference/api/brands/#update-theme),  only the next fields could be presented in a request body:
```
primaryColorHex
primaryColorContrastHex
secondaryColorHex
secondaryColorContrastHex
signInPageTouchPointVariant
endUserDashboardTouchPointVariant
errorPageTouchPointVariant
emailTemplateTouchPointVariant
```
So a new `ThemeSettings` object is created.
[Related Sluck thread](https://okta.slack.com/archives/G7VT7GL0J/p1635864440190900)
> Brands API: fixes for Java SDK

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
We are missing the IDP policy rule action model. This adds a IdpPolicyRuleAction and its providers array of elements IdpPolicyRuleAction
https://developer.okta.com/docs/reference/api/policy/#policy-action-object
https://github.com/okta/okta-sdk-golang/issues/279
https://github.com/okta/okta-sdk-golang/pull/280
> Adds missing policy rule action for IDPs

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
- New Paths:
- `GET /api/v1/brands/{brandId}/templates/email`
- operation added: `listEmailTemplates`
- `GET /api/v1/brands/{brandId}/templates/email/{templateName}`
- operation added: `getEmailTemplate`
- `DELETE & GET & POST /api/v1/brands/{brandId}/templates/email/{templateName}/customizations`
- operations added: `deleteEmailTemplateCustomizations`, `listEmailTemplateCustomizations`, `createEmailTemplateCustomization`
- `DELETE & GET & PUT /api/v1/brands/{brandId}/templates/email/{templateName}/customizations/{customizationId}`
- operations added: `deleteEmailTemplateCustomization`, `getEmailTemplateCustomization`, `updateEmailTemplateCustomization`
- `GET /api/v1/brands/{brandId}/templates/email/{templateName}/customizations/{customizationId}/preview`
- operation added: …
> Include Email Template

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Avoiding merge commit hassles and redoing PR #110
https://developer.okta.com/docs/reference/api/idps/#add-apple-identity-provider
Related to https://github.com/okta/terraform-provider-okta/issues/841
- Adds `privateKey` and `teamId` to `IdentityProviderCredentialsSigning`
- Adds to `APPLE` to the enum in `FactorProvider`
- Adds to `APPLE` to the enum in `LogCredentialProvider`
> Redo Apple IDp values

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- package.json
- resources/spec.yaml
`_links` property was omitted from ResponseLinks spec for `GET /api/v1/users/${id}/linkedObjects/${associated.name}` https://developer.okta.com/docs/reference/api/linked-objects/#get-associated-linked-object-values
Tested out in okta-sdk-golang
https://github.com/okta/okta-sdk-golang/pull/285
and okta terraform provider
https://github.com/okta/terraform-provider-okta/pull/1001/files
https://github.com/okta/terraform-provider-okta/blob/7ccb6effb57da5b8fef2860bd286e53f10b05da0/okta/resource_okta_link_value.go#L88
> Linked objects response links

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Authenticator properties specific to the Duo authenticator. They are publicly documented in the Okta API docs.
Properties
- `provider.configuration.host`
- `provider.configuration.integrationKey`
- `provider.configuration.secretKey`
References
- Okta Dev Docs https://github.com/okta/okta-developer-docs/pull/3381
- Published Okta Dev Docs https://developer.okta.com/docs/reference/api/authenticators-admin/#authenticator-object
- okta-sdk-golang generated from this spec https://github.com/okta/okta-sdk-golang/pull/311
> Duo authenticator properties

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Problem:
Python SDK does not have the urn:ietf:params:oauth:grant-type:saml2-bearer [OAuthGrantType here](https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/models/o_auth_grant_type.py#L24-L36) that the customer cannot create such an OAuth2 Client using the Python SDK.
This PR adds the missing SAML2Bearer grant type and a few other which were also missing:
- urn:ietf:params:oauth:grant-type:device_code
- urn:ietf:params:oauth:grant-type:saml2-bearer
- urn:ietf:params:oauth:grant-type:token-exchange
- interaction_code
> Adding new OAuthGrantTypes

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Adds `pkce_required` boolean which is now present on the `ApplicationCredentialsOAuthClient` model
https://developer.okta.com/docs/reference/api/apps/#oauth-credential-object
okta-sdk-golang https://github.com/okta/okta-sdk-golang/pull/329
> ApplicationCredentialsOAuthClient `pkce_required` boolean

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Adds client secrets to the Application model
https://developer.okta.com/docs/reference/api/apps/#application-client-secret-management-operations
Added missing 2.14.0 release notes to changelog
okta-sdk-golang https://github.com/okta/okta-sdk-golang/pull/330
> Application model client secrets

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Add attribute uiSchemaId to the Profile Enrollment Action Object
Ref: https://github.com/okta/okta-developer-docs/pull/3529
API docs: [Profile Enrollment Action object](https://developer.okta.com/docs/reference/api/policy/#profile-enrollment-action-object)
> Add attribute uiSchemaId to the Profile Enrollment Action Object

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
Support `POST /api/v1/authenticators`
https://developer.okta.com/docs/reference/api/authenticators-admin/#create-authenticator
Proven in:
- https://github.com/okta/okta-sdk-golang/pull/345
- https://github.com/okta/terraform-provider-okta/pull/1379
> Support `POST /api/v1/authenticators`

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
`MFA_ENROLL` policy type was missing in the spec, this will allow users to get `MFA_ENROLL` policies, referring to this: https://github.com/okta/okta-sdk-python/issues/288
Already implemented in OASV3 - took inspiration from there
> Add MFA_ENROLL policy type

- package.json
With these fields npm package page can link to the public github repo.
> chore: add homepage and repository fields in package.json

- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
This is a public field and needed by the TF provider https://github.com/okta/terraform-provider-okta/issues/1401
Tests are passing for golang SDK feature branch that makes uses of this spec: [[URL to feature branch]](https://github.com/okta/okta-sdk-golang/pull/361)
> Adding samlSignedRequestEnabled boolean field to SAML app settings

- CHANGELOG.md
- dist/spec.json
- dist/spec.yaml
- resources/spec.yaml
- Add missing properties to applicationsettingsapplication per the reference docs: https://developer.okta.com/docs/reference/api/apps/#settings-4
- Add signed_nonce factor type per the reference docs: https://developer.okta.com/docs/reference/api/factors/#factor-type
Related to OKTA-588345 and OKTA-588345
Represents python sdk changes made here: https://github.com/okta/okta-sdk-python/pull/366
> Fixes for python
